version: '3'

services:
  host:
    build: 
      context: .
      dockerfile: ./host/Dockerfile
    ports:
      - "50051:50051"
    networks:
      autogen_net:
        ipv4_address: 172.20.0.10
    environment:
      - HOST_ADDRESS=0.0.0.0:50051

  worker1:
    build: 
      context: .  # Build context is root directory
      dockerfile: ./worker1/Dockerfile
    depends_on:
      - host
    networks:
      autogen_net:
        ipv4_address: 172.20.0.11
    environment:
      - HOST_ADDRESS=172.20.0.10:50051

  worker2:
    build:
      context: .  # Build context is root directory
      dockerfile: ./worker2/Dockerfile
    depends_on:
      - host
    networks:
      autogen_net:
        ipv4_address: 172.20.0.12
    environment:
      - HOST_ADDRESS=172.20.0.10:50051
      - OPENAI_API_KEY=${OPENAI_API_KEY}

networks:
  autogen_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24